### PR TITLE
Ensure lsb-release is installed for Debian codename in install_deb

### PR DESCRIPTION
**Pull request by chewi**
lsb-release must be present for `node['lsb']['codename']` to be populated. It is missing when the "standard system utilities" are not selected at install time. The lsb Ohai plugin must also be reloaded
for this to take effect immediately.

### CODE REVIEW

**Comment by chewi** [comment]
Hmm I've rebased this but actually it doesn't seem effective any more. I will investigate tomorrow.

**Comment by chewi** [comment]
Figured it out. Please merge! :smile_cat:

**Comment by ice799** [comment]
Hi @chewi! I'm open to merging this, but can you help me understand why `lazy`  was added? Thanks!

**Comment by chewi** [comment]
The first one is because `node['lsb']['codename']` is set when the Ohai plugin is reloaded at converge time. The second one… uh… it's been too long! I do remember working on this though and there definitely was a reason.

**Comment by ice799** [comment]
No worries, I'm going to re-run the test suite now without the `lazy` added to the GPG stuff and see how it goes. If everything passes, I'll merge it without the GPG related changes. Is that OK?

**Comment by ice799** [comment]
Ah, OK. Ummm. Yea, nothing is ever simple I guess ;)  Looks like this adds the lsb stuff for deb only, but it is also used for RPMs. I guess this would need to be modified a bit to install lsb in both cases. Hm.

**Comment by chewi** [comment]
No need, `install_endpoint_params` is called for RPMs but only the Debian clause uses `node['lsb']['codename']`. RPM-based distros don't have code names like Debian does and the version number is used in the URLs instead.

**Comment by ice799** [comment]
tests all passed, so i merged this. thanks for sending this PR @chewi!

**Pull request merged**
