### PR TITLE
Proxy Implementation and RPM Fixes

### PR DESCRIPTION
**Pull request by afiune**
This commit is implementing proxy settings if you have it
on your environment and also it fixes some issues that we
had when trying to pull down packages (RPM) for rhel family.

### CODE REVIEW

**Comment by jmaziarz** [comment]
+1 for proxy support

**Comment by icberg7** [comment]
Will this add proxy configuration to the yum repo config file? I think `proxy=` must also exist in the yum.repos.d/config file for the machine to be able to pull down RPMs via a proxy.

**Comment by damacus** [comment]
This looks great, I was about to open an issue about proxy support. Any chance this can get merged into master please? (after merge conflicts are resolved of course)

**Comment by afiune** [comment]
Ups.. I forgot about this! I can fix the conflicts in a bit :smile:

**Comment by afiune** [comment]
Done! Rebased against master.. :smile: Anybody know who I need to ping to get this under review?

**Comment by afiune** [comment]
Perhaps @ice799 ..

**Comment by damacus** [comment]
I was also wondering why we couldn't just pop out to the yum resource and let that do the installation of the packagecloud repo?  
As the readme suggests there's currently a few work arounds when a box is also using the yum resource. 
I couldn't find any particular reason why we're practically reimplementing the yum bit, unless I'm missing something here? (which is entirely likely!)

**Comment by damacus** [comment]
@icberg7 you'll need to configure that using the yum cookbook a la:
```
yum_globalconfig '/etc/yum.conf' do
  proxy 'proxy:port'
end
```

**Comment by damacus** [comment]
@afiune I've just tried to get this working behind the proxy here. I've set http_proxy but am getting a timeout still. 

Anything I'm missing?

**Comment by icberg7** [comment]
@damacus the company I work for maintains internal mirrors of common repositories,so I don't want to configure the yum proxy at a global/server level; I just need to be able to run the package cloud repos through a proxy.

**Pull request closed without merging**
